// Author/creator: nattapat2871 (https://nattapat2871.me)
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import test from 'node:test'
import AdmZip from 'adm-zip'

const mainSource = await readFile(new URL('../electron/main.ts', import.meta.url), 'utf8')
const preloadSource = await readFile(new URL('../electron/preload.ts', import.meta.url), 'utf8')
const appSource = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8')
const mainEntrySource = await readFile(new URL('../src/main.tsx', import.meta.url), 'utf8')
const appTextSource = await readFile(new URL('../src/appText.ts', import.meta.url), 'utf8')
const partnerServersSource = await readFile(new URL('../shared/partnerServers.ts', import.meta.url), 'utf8')
const installerSource = await readFile(new URL('../build/installer.nsh', import.meta.url), 'utf8')
const skinPageSource = await readFile(new URL('../src/components/SkinPage.tsx', import.meta.url), 'utf8')
const launcherErrorBoundarySource = await readFile(new URL('../src/components/LauncherErrorBoundary.tsx', import.meta.url), 'utf8')
const cssSource = await readFile(new URL('../src/index.css', import.meta.url), 'utf8')
const indexHtml = await readFile(new URL('../index.html', import.meta.url), 'utf8')

test('boot progress entries use a monotonic ref instead of impure timestamp keys', () => {
  assert.match(appSource, /const bootLogSequenceRef = useRef\(0\)/)
  assert.match(appSource, /const eventId = `\$\{bootStartedAt\}-\$\{\+\+bootLogSequenceRef\.current\}`/)
  assert.doesNotMatch(appSource, /id: `\$\{Date\.now\(\)\}-\$\{progressValue\}-\$\{text\}`/)
})

test('isolated UI QA can bypass the single-instance lock only in development', () => {
  assert.match(mainSource, /const allowIsolatedUiQaInstance = !app\.isPackaged && process\.env\.NAMLAUNCHER_UI_QA === '1'/)
  assert.match(mainSource, /const hasSingleInstanceLock = allowIsolatedUiQaInstance \|\| app\.requestSingleInstanceLock\(\)/)
  assert.match(mainSource, /if \(allowIsolatedUiQaInstance\) \{[\s\S]*Skipped legacy data migration for isolated UI QA\.[\s\S]*\} else \{[\s\S]*migrateInstallLocalUserData\(\)[\s\S]*migrateLegacyAccounts\(\)/)
})

test('resets the main scroll position when navigating between launcher pages and instances', () => {
  assert.match(appSource, /const mainScrollRef = useRef<HTMLElement \| null>\(null\)/)
  assert.match(appSource, /useEffect\(\(\) => \{\s*mainScrollRef\.current\?\.scrollTo\(\{ top: 0, behavior: 'auto' \}\)\s*if \(activeView !== 'settings'\) pendingDiscordAccountFocusRef\.current = false\s*\}, \[activeView\]\)/)
  assert.match(appSource, /const openInstanceDetail = \(instanceId: string\) => \{[\s\S]*mainScrollRef\.current\?\.scrollTo\(\{ top: 0, behavior: 'auto' \}\)/)
  assert.match(appSource, /<main ref=\{mainScrollRef\} className="min-h-0 flex-1 overflow-y-auto p-6">/)
})

test('retries transient CurseForge proxy failures and reports a user-facing install error', () => {
  assert.match(mainSource, /const requestCurseForge = async <T>/)
  assert.match(mainSource, /for \(let attempt = 0; attempt < 3; attempt \+= 1\)/)
  assert.match(mainSource, /status === 503/)
  assert.match(mainSource, /status === 451/)
  assert.match(mainSource, /trustedIpcHandle\('install-curseforge-modpack'[\s\S]*getCurseForgeFailureMessage/)
  assert.doesNotMatch(preloadSource, /Request failed with status code \(\?:403\|429\|451\|502\|503\|504\)/)
})

test('queues author-blocked CurseForge modpack files for browser download without bypassing distribution settings', () => {
  assert.match(mainSource, /const assertCurseForgeDistributionAllowed = \(mod: CurseForgeMod\) => \{/)
  assert.match(mainSource, /const isCurseForgeDownloadUnavailableStatus = \(status\?: number\) => status === 403 \|\| status === 404 \|\| status === 451/)
  assert.match(mainSource, /type CurseForgeManualDownload = \{/)
  assert.match(mainSource, /const createCurseForgeManualDownload = \(/)
  assert.match(mainSource, /\/download\/\$\{file\.id\}/)
  assert.match(mainSource, /childMod\.allowModDistribution === false/)
  assert.match(mainSource, /manualDownloads\.push\(manualDownload\)/)
  assert.match(mainSource, /detail: childFile\.fileName/)
  assert.match(mainSource, /isCurseForgeManualDownloadRequiredError\(err\)/)
  assert.match(mainSource, /manualDownloadDirectory: app\.getPath\('downloads'\)/)
  assert.match(mainSource, /trustedIpcHandle\('import-curseforge-manual-download'/)
  assert.match(mainSource, /verifyManualCurseForgeDownload\(targetPath, item\)/)
  assert.match(mainSource, /blockedFiles/)
  assert.match(appSource, /manualDownload\.title/)
  assert.match(appSource, /window\.electron\.importCurseForgeManualDownload/)
  assert.match(appSource, /manualDownload\.action\.openAll/)
  assert.match(appSource, /manualDownload\.status\.complete/)
  assert.match(appSource, /cancelManualDownloadsAndDeleteInstance/)
  assert.match(preloadSource, /importCurseForgeManualDownload/)
})

test('reports modpack progress as one aggregate install instead of per-file bars', () => {
  assert.match(mainSource, /onProgress\?: \(percent: number\) => void/)
  assert.match(mainSource, /downloadModpackArchive\(version, signal, \(percent, detail\) => \{/)
  assert.match(mainSource, /const fileStart = 15 \+ \(\(indexFile \/ Math\.max\(1, packFiles\.length\)\) \* 70\)/)
  assert.match(mainSource, /downloadModpackIndexFile\(file, gameDirectory, signal, \(percent, detail\) => \{/)
  assert.match(mainSource, /const fileStart = 10 \+ \(\(index \/ Math\.max\(1, packFiles\.length\)\) \* 75\)/)
  assert.match(mainSource, /downloadCurseForgeFileToDirectory\(childMod, childFile, childType, installDirectory, signal, \(percent, detail\) => \{/)
  assert.match(mainSource, /task: Math\.round\(fileStart \+ \(\(fileEnd - fileStart\) \* \(Math\.min\(Math\.max\(percent, 0\), 100\) \/ 100\)\)\)/)
})

test('uses launcher-styled confirmation dialogs instead of native browser confirms', () => {
  assert.doesNotMatch(appSource, /window\.confirm/)
  assert.doesNotMatch(skinPageSource, /window\.confirm/)
  assert.match(appSource, /type ConfirmDialogState = \{/)
  assert.match(appSource, /const \[confirmDialog, setConfirmDialog\]/)
  assert.match(appSource, /role="dialog"[\s\S]*confirm-dialog-title/)
  assert.match(appSource, /deleteInstanceFiles/)
  assert.match(appSource, /deleteContentFiles/)
  assert.match(skinPageSource, /skinDeleteTargetId/)
  assert.match(skinPageSource, /aria-labelledby="skin-delete-title"/)
})

test('shows progress while a local mrpack is being opened, validated, and extracted', () => {
  const importer = mainSource.slice(
    mainSource.indexOf('const installLocalMrpack = async'),
    mainSource.indexOf('const mapCurseForgeProject')
  )
  assert.match(importer, /task: 2[\s\S]*Reading/)
  assert.match(importer, /task: 6[\s\S]*Validating modpack index/)
  assert.match(mainSource, /task: 86 \+ Math\.round/)
})

test('keeps local mrpack import blocked behind an explicit progress dialog', () => {
  assert.match(appSource, /const mrpackImportProgressModal = importingMrpack \? \(/)
  assert.match(appSource, /role="dialog" aria-modal="true" aria-labelledby="mrpack-import-title"/)
  assert.match(appSource, /onClick=\{\(\) => cancelActiveInstall\(\)\}[\s\S]*aria-label=\{t\('mrpack\.progress\.cancel'\)\}/)
  assert.match(appSource, /\{mrpackImportProgressModal\}/)
})

test('keeps content update busy indicators active across batch updates', () => {
  assert.match(appSource, /const \[updatingProjectIds, setUpdatingProjectIds\] = useState<string\[\]>\(\[\]\)/)
  assert.match(appSource, /const activeContentUpdatesRef = useRef\(0\)/)
  assert.match(appSource, /const setProjectUpdateBusy = \(projectId: string, busy: boolean\) => \{/)
  assert.match(appSource, /for \(let index = 0; index < updates\.length; index \+= 1\)[\s\S]*setProjectUpdateBusy\(update\.projectId, true\)[\s\S]*finally \{[\s\S]*setProjectUpdateBusy\(update\.projectId, false\)/)
  assert.match(appSource, /disabled=\{busy \|\| updatingThis \|\| contentBlocked \|\| \(updatingInstanceId === currentTarget\.id && !updatingThis\)\}/)
})

test('loads instance content on demand and opens screenshots in a zoomable viewer', () => {
  assert.match(appSource, /type InstanceContentCache = Record<string, Partial<Record<InstanceContentKind, InstanceContentItem\[\]>>>/)
  assert.match(appSource, /const INSTANCE_CONTENT_KINDS: InstanceContentKind\[\] = \['mods', 'resourcepacks', 'shaderpacks', 'screenshots'\]/)
  assert.doesNotMatch(appSource, /const preloadInstanceContent = async/)
  assert.doesNotMatch(appSource, /preloadInstanceContent\(loadedInstances\)/)
  assert.match(appSource, /if \(!bootReady \|\| activeView !== 'instances' \|\| instancePanelView !== 'content'\) return/)
  assert.match(appSource, /if \(kind === 'screenshots'\) return/)
  assert.match(appSource, /instanceContentCacheRef\.current\[target\.id\]\?\.\[kind\]/)
  assert.match(appSource, /const \[selectedScreenshot, setSelectedScreenshot\] = useState<InstanceContentItem \| null>\(null\)/)
  assert.match(appSource, /const \[screenshotZoom, setScreenshotZoom\] = useState\(1\)/)
  assert.match(appSource, /const \[screenshotPan, setScreenshotPan\] = useState<ScreenshotPan>\(\{ x: 0, y: 0 \}\)/)
  assert.match(appSource, /const \[screenshotDragging, setScreenshotDragging\] = useState\(false\)/)
  assert.match(appSource, /screenshotPanFrameRef/)
  assert.match(appSource, /window\.requestAnimationFrame/)
  assert.match(appSource, /const startScreenshotPan = \(event: React\.PointerEvent<HTMLDivElement>\) => \{/)
  assert.match(appSource, /const moveScreenshotPan = \(event: React\.PointerEvent<HTMLDivElement>\) => \{/)
  assert.match(appSource, /scheduleScreenshotPan\(\{/)
  assert.match(appSource, /transform: `translate3d\(\$\{screenshotPan\.x\}px, \$\{screenshotPan\.y\}px, 0\) scale\(\$\{screenshotZoom\}\)`/)
  assert.match(appSource, /onClick=\{\(\) => openScreenshotViewer\(item\)\}/)
  assert.match(appSource, /onPointerDown=\{startScreenshotPan\}/)
  assert.match(appSource, /onWheel=\{\(event\) => \{[\s\S]*adjustScreenshotZoom/)
  assert.match(appSource, /t\('screenshot\.zoomIn'\)/)
  assert.match(appSource, /className="relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-md border border-slate-700/)
})

test('renames offline accounts, confirms account removal, and shows Microsoft login progress', () => {
  assert.doesNotMatch(appSource, /Cracked/)
  assert.doesNotMatch(appSource, /Offline \/ local/)
  assert.match(appTextSource, /'auth\.offline\.title': 'Offline account'/)
  assert.match(appTextSource, /'account\.type\.offline': 'Offline account'/)
  assert.match(appSource, /const \[microsoftLoginLoading, setMicrosoftLoginLoading\] = useState\(false\)/)
  assert.match(appSource, /setMicrosoftLoginLoading\(true\)[\s\S]*window\.electron\.loginMicrosoft\(\)/)
  assert.match(appSource, /t\('auth\.microsoft\.loading'\)/)
  assert.match(appSource, /const removeAccount = \(account: Account\) => \{[\s\S]*setConfirmDialog\(/)
  assert.match(appSource, /title: t\('account\.remove\.title'\)/)
  assert.match(appSource, /<MicrosoftMark className="h-4 w-4" \/>/)
})

test('combines game logs and separates local game issues from owned launcher-component errors', () => {
  assert.match(mainSource, /const buildInstanceCrashLog = \(instance: ReturnType<typeof normalizeInstance>, since = 0\) => \{/)
  assert.match(mainSource, /const combinedLogPath = path\.join\(instanceRoot, 'crash_logs\.txt'\)/)
  assert.match(mainSource, /launcherLogPath: logPath/)
  assert.match(mainSource, /mainWindow\?\.webContents\.send\('launch-error', error\)/)
  assert.match(mainSource, /const failure = classifyMinecraftProcessFailure\(error, diagnosis, \{/)
  assert.match(mainSource, /if \(failure\.reportPolicy === 'automatic'\) \{[\s\S]*const reportTitle = failure\.code === 'namlauncher-runtime-failure'[\s\S]*NamLauncher selected an incompatible Java runtime[\s\S]*NamLauncher game component failed[\s\S]*publishLauncherError\(error, 'minecraft-exit', reportTitle, \{[\s\S]*playerName: closedGame\?\.playerName/)
  assert.match(mainSource, /sendMinecraftGameIssue\(\{[\s\S]*classification: failure/)
  assert.match(appSource, /const launcherErrorIsMinecraft = Boolean\(launcherErrorReport\?\.context\?\.startsWith\('minecraft'\)\)/)
  assert.match(appSource, /const minecraftGameIssueModal = minecraftGameIssue \? \(/)
})

test('keeps Modrinth requests direct-first with bounded retry, pacing, and metadata caches', () => {
  assert.match(mainSource, /const MODRINTH_MAX_CONCURRENT_REQUESTS = 4/)
  assert.match(mainSource, /const MODRINTH_MIN_REQUEST_GAP_MS = 200/)
  assert.match(mainSource, /const MODRINTH_DIRECT_TIMEOUT_MS = 6500/)
  assert.match(mainSource, /const MODRINTH_PROXY_TIMEOUT_MS = 8000/)
  assert.match(mainSource, /const MODRINTH_PROXY_MAX_ATTEMPTS = 2/)
  assert.match(mainSource, /const MODRINTH_METADATA_MAX_BYTES = 16 \* 1024 \* 1024/)
  assert.match(mainSource, /const PROJECT_SEARCH_CACHE_STALE_TTL_MS = 24 \* 60 \* 60 \* 1000/)
  assert.match(mainSource, /const MODRINTH_VERSION_CACHE_LIMIT = 256/)
  assert.match(mainSource, /const MODRINTH_PROXY_BASE = `\$\{STATS_API_BASE\}\/api\/v1\/modrinth`/)
  assert.match(mainSource, /const MODRINTH_PROXY_FALLBACK_STATUSES = new Set\(\[404, 408, 425, 500, 502, 503, 504\]\)/)
  assert.match(mainSource, /const MODRINTH_RETRY_STATUSES = new Set\(\[408, 425, 429, 500, 502, 503, 504\]\)/)
  assert.match(mainSource, /ENETUNREACH/)
  assert.match(mainSource, /EHOSTUNREACH/)
  assert.match(mainSource, /ECONNREFUSED/)
  assert.match(mainSource, /ERR_NETWORK/)
  assert.match(mainSource, /ERR_SOCKET_CLOSED/)
  assert.match(mainSource, /UNABLE_TO_GET_ISSUER_CERT_LOCALLY/)
  assert.match(mainSource, /const shouldRetryModrinthRequest = \(error: unknown\) => \{/)
  assert.match(mainSource, /const getModrinthProxyUrl = \(url: string\) => \{/)
  assert.match(mainSource, /const shouldFallbackToModrinthProxy = \(error: unknown\) => \{/)
  assert.match(mainSource, /const acquireModrinthSlot = \(signal\?: AbortSignal\)/)
  assert.match(mainSource, /let nextModrinthRequestAt = 0/)
  assert.match(mainSource, /signal\?\.addEventListener\('abort', abort, \{ once: true \}\)/)
  assert.match(mainSource, /const waitForModrinthRetry = \(milliseconds: number, signal\?: AbortSignal\)/)
  assert.match(mainSource, /const requestModrinthProxyWithRetry = async <T>/)
  assert.match(mainSource, /attempt < MODRINTH_PROXY_MAX_ATTEMPTS/)
  assert.match(mainSource, /await waitForModrinthRetry\(retryDelay, config\.signal\)/)
  assert.match(mainSource, /return await requestModrinthEndpoint<T>\(url, config, 'direct'\)/)
  assert.match(mainSource, /falling back to the NamLauncher proxy/)
  assert.match(mainSource, /return requestModrinthProxyWithRetry<T>\(proxyUrl, config\)/)
  assert.match(mainSource, /const getModrinthFailureMessage = \(err: unknown, operation: 'search' \| 'download'\) => \{/)
  assert.match(mainSource, /const requestModrinth = async <T>/)
  assert.match(mainSource, /maxContentLength: MODRINTH_METADATA_MAX_BYTES/)
  assert.match(mainSource, /const setCachedModrinthVersions = \(cacheKey: string, versions: ModrinthVersion\[\]\) => \{/)
  assert.match(mainSource, /while \(modrinthVersionCache\.size > MODRINTH_VERSION_CACHE_LIMIT\)/)
  assert.match(mainSource, /activeModrinthSearchController\?\.abort\(\)/)
  assert.match(mainSource, /getCachedProjectSearchResult\(cacheKey, true\)/)
  assert.match(mainSource, /return \{ \.\.\.staleResult, stale: true \}/)
  assert.match(mainSource, /controller\.signal\.aborted && axios\.isCancel\(err\)[\s\S]*return \{ hits: \[\], total_hits: 0, canceled: true \}/)
  assert.match(mainSource, /Modrinth search failed after all network fallbacks/)
  assert.match(mainSource, /trustedIpcHandle\('search-modrinth'[\s\S]*getModrinthFailureMessage\(err, 'search'\)/)
})

test('verifies Modrinth download candidates before replacing installed files', () => {
  assert.match(mainSource, /const DOWNLOAD_INTEGRITY_ERROR_CODE = 'EINTEGRITY'/)
  assert.match(mainSource, /const createModrinthCandidateValidator = \(/)
  assert.match(mainSource, /validateCandidate\?: DownloadCandidateValidator/)

  const downloadSection = mainSource.slice(
    mainSource.indexOf('const downloadFile = async ('),
    mainSource.indexOf('const getDeclaredDownloadLimit =')
  )
  const validationIndex = downloadSection.indexOf('await validateCandidate(tempPath)')
  const replacementIndex = downloadSection.indexOf('replaceFileWithCandidate(tempPath, filePath)')
  assert.ok(validationIndex >= 0, 'candidate validation must run inside downloadFile')
  assert.ok(replacementIndex > validationIndex, 'candidate validation must finish before the installed file is replaced')
  assert.doesNotMatch(downloadSection, /fs\.rmSync\(filePath, \{ force: true \}\)/)
  assert.match(downloadSection, /shouldRetryDownloadError\(err\)/)
  assert.match(downloadSection, /beforeRedirect:/)
  assert.match(downloadSection, /await waitForModrinthRetry\(retryDelay, signal\)/)

  assert.match(mainSource, /getDeclaredDownloadLimit\(file\.size\),\s*createModrinthCandidateValidator\(file, filename\)/)
  assert.match(mainSource, /getDeclaredDownloadLimit\(file\.size\),\s*createModrinthCandidateValidator\(file, file\.filename\)/)
  assert.match(mainSource, /const replaceFileWithCandidate = \(candidatePath: string, targetPath: string\) => \{/)
  assert.match(mainSource, /fs\.renameSync\(targetPath, backupPath\)/)
  assert.match(mainSource, /fs\.renameSync\(backupPath, targetPath\)/)
  assert.match(mainSource, /const assertModrinthFileVerifiable = \(/)
  assert.match(mainSource, /return false\s*\n\}/)
  assert.match(mainSource, /const supportedUrls = Array\.from\(new Set\(file\.downloads\.filter/)
  assert.match(mainSource, /All supported download mirrors failed/)
  assert.match(mainSource, /const createdPaths = new Set<string>\(\)/)
  assert.match(mainSource, /if \(downloaded\.created\) createdPaths\.add\(downloaded\.path\)/)
  assert.match(mainSource, /if \(isPathInside\(createdPath, installDirectory\) && fs\.existsSync\(createdPath\)\)/)
})

test('uses the operating system certificate store for Node HTTPS requests', () => {
  assert.match(mainSource, /import https from 'https'/)
  assert.match(mainSource, /import tls from 'tls'/)
  assert.match(mainSource, /const configureSystemCertificateStore = \(\) => \{/)
  assert.match(mainSource, /getCACertificates\('system'\)/)
  assert.match(mainSource, /setDefaultCACertificates\?\.\(trustedCertificates\)/)
  assert.match(mainSource, /https\.globalAgent\.options\.ca = trustedCertificates/)
  assert.match(mainSource, /axios\.defaults\.httpsAgent = https\.globalAgent/)
  assert.doesNotMatch(mainSource, /rejectUnauthorized:\s*false/)
})

test('allows launcher log text to be selected and copied', () => {
  assert.match(appSource, /className="nam-selectable h-\[460px\] cursor-text/)
  assert.match(cssSource, /\.nam-selectable,[\s\S]*user-select: text/)
})

test('keeps renderer crashes from blanking the launcher window', () => {
  assert.match(mainEntrySource, /LauncherErrorBoundary/)
  assert.match(mainEntrySource, /<LauncherErrorBoundary>[\s\S]*<App \/>[\s\S]*<\/LauncherErrorBoundary>/)
  assert.match(launcherErrorBoundarySource, /class LauncherErrorBoundary extends React\.Component/)
  assert.match(launcherErrorBoundarySource, /getDerivedStateFromError/)
  assert.match(launcherErrorBoundarySource, /componentDidCatch/)
  assert.match(launcherErrorBoundarySource, /copyErrorReport/)
  assert.match(launcherErrorBoundarySource, /window\.location\.reload/)
  assert.match(mainSource, /render-process-gone'[\s\S]*details\.reason === 'clean-exit'/)
  assert.match(mainSource, /MAX_RENDERER_RECOVERIES_PER_WINDOW = 2/)
  assert.match(mainSource, /rendererRecoveryAttempts = rendererRecoveryAttempts\.filter/)
  assert.match(mainSource, /windowForRenderer\.webContents\.reload\(\)/)
})

test('checks launcher updates within ten minutes without requiring a restart', () => {
  assert.match(mainSource, /LAUNCHER_UPDATE_CHECK_INTERVAL_MS = 10 \* 60 \* 1000/)
  assert.match(mainSource, /setInterval\([\s\S]*publishLauncherUpdate\(\)[\s\S]*LAUNCHER_UPDATE_CHECK_INTERVAL_MS/)
  assert.match(mainSource, /webContents\.send\('launcher-update', update\)/)
  assert.match(preloadSource, /ipcRenderer\.on\('launcher-update'/)
  assert.match(appSource, /onLauncherUpdate\(\(update\) =>/)
})

test('exposes update checks and Discord settings without a startup welcome notice', () => {
  assert.match(appSource, /const checkForLauncherUpdateNow = async \(\) =>/)
  assert.match(appSource, /window\.electron\.checkLauncherUpdate\(\)/)
  assert.match(appSource, /settings\.update\.check/)
  assert.match(appSource, /update\.error[\s\S]*status\.updateCheckFailed/)
  assert.match(appSource, /const DiscordLogo =/)
  assert.match(appSource, /onClick=\{openDiscordAccountSettings\}/)
  assert.match(appSource, /onAnimationComplete=\{focusDiscordAccountSection\}/)
  assert.match(appSource, /ref=\{discordAccountSectionRef\} id="discord-account-settings" tabIndex=\{-1\}/)
  assert.match(appSource, /section\.scrollIntoView\(\{ behavior: reduceMotion \? 'auto' : 'smooth', block: 'start' \}\)/)
  assert.match(appSource, /section\.focus\(\{ preventScroll: true \}\)/)
  assert.match(appSource, /launcherDiscordAccount\.profile\.avatarUrl/)
  assert.match(appSource, /settings\.discordAccount\.login/)
  assert.match(appSource, /NAMLAUNCHER_DISCORD_URL = 'https:\/\/namlauncher\.nattapat2871\.me\/discord'/)
  assert.match(appSource, /topbar\.discord/)
  assert.match(appSource, /settings\.discord\.join/)
  assert.match(appSource, /const requestDisconnectLauncherDiscord = \(\) => \{[\s\S]*setConfirmDialog\(/)
  assert.match(appSource, /settings\.discordAccount\.logoutTitle/)
  assert.doesNotMatch(appSource, /showStartupNotice|startupNoticeShownRef|startup\.checkUpdates/)
  assert.match(appSource, /showFirstRunSetup/)
  assert.match(appTextSource, /'settings\.discordAccount\.logoutConfirm'/)
  assert.doesNotMatch(appTextSource, /'startup\.title'/)
  assert.match(appTextSource, /'topbar\.discord': 'เข้า Discord'/)
  assert.match(appTextSource, /'settings\.discord\.join': 'เข้า Discord'/)
})

test('shows a blocking launcher update prompt and opens downloaded Windows installers directly', () => {
  const updaterSource = mainSource.slice(
    mainSource.indexOf('const assertTrustedLauncherUpdateUrl'),
    mainSource.indexOf('const getLauncherWebsiteStats')
  )
  assert.match(mainSource, /const assertTrustedLauncherUpdateUrl/)
  assert.match(mainSource, /trustedIpcHandle\('install-launcher-update'/)
  assert.match(mainSource, /mainWindow\.webContents\.send\('launcher-update-progress'/)
  assert.match(updaterSource, /state: 'opening-installer'/)
  assert.match(updaterSource, /state: 'installer-opened'/)
  assert.match(updaterSource, /getLauncherUpdateDownloadDirectory/)
  assert.match(mainSource, /const UPDATE_CLEANUP_FILE = 'pending-launcher-update-cleanup\.json'/)
  assert.match(mainSource, /path\.join\(userDataPath, UPDATE_FOLDER_NAME\)/)
  assert.match(mainSource, /cleanupPendingLauncherUpdateInstaller\(\)/)
  assert.match(mainSource, /getLauncherUpdateCleanupRetryDelay\(err, attempt\)/)
  assert.match(mainSource, /setTimeout\(\(\) => cleanupPendingLauncherUpdateInstaller\(attempt \+ 1\), retryDelay\)/)
  assert.match(mainSource, /cleanupRetryTimer\.unref\?\.\(\)/)
  assert.match(updaterSource, /writePendingLauncherUpdateCleanup\(downloadedInstallerPath, update\.latestVersion\)/)
  assert.match(updaterSource, /assertDownloadedLauncherInstaller/)
  assert.match(updaterSource, /normalizeLauncherInstallerSha256\(update\.installerSha256\)/)
  assert.match(updaterSource, /assertFileSha256\(installerPath, expectedSha256\)/)
  assert.match(updaterSource, /header\.toString\('ascii'\) !== 'MZ'/)
  assert.match(updaterSource, /shell\.openPath\(installerPath\)/)
  assert.match(updaterSource, /installerOpened: true/)
  assert.match(updaterSource, /willRestart: true/)
  assert.match(updaterSource, /quitLauncherForUpdateInstaller\(\)/)
  assert.match(updaterSource, /requestAppQuit\(\)/)
  assert.doesNotMatch(updaterSource, /Start-Process/)
  assert.doesNotMatch(updaterSource, /powershell\.exe/)
  assert.doesNotMatch(updaterSource, /cmd\.exe/)
  assert.doesNotMatch(updaterSource, /\/S \$installMode/)
  assert.doesNotMatch(updaterSource, /app\.exit\(0\)/)
  assert.doesNotMatch(mainSource, /trustedIpcHandle\('apply-launcher-update'/)
  assert.match(preloadSource, /installLauncherUpdate: \(\) => invoke\('install-launcher-update'\)/)
  assert.doesNotMatch(preloadSource, /applyLauncherUpdate/)
  assert.match(preloadSource, /ipcRenderer\.on\('launcher-update-progress'/)
  assert.doesNotMatch(installerSource, /StdUtils\.ExecShellAsUser/)
  assert.match(appSource, /launcherUpdatePromptVisible/)
  assert.match(appSource, /setDismissedLauncherUpdateVersion\(launcherUpdate\.latestVersion\)/)
  assert.match(appSource, /const openLauncherUpdatePrompt = \(\) => \{[\s\S]*setDismissedLauncherUpdateVersion\(''\)/)
  assert.match(appSource, /onClick=\{openLauncherUpdatePrompt\}/)
  assert.match(appSource, /const openLauncherUpdateDownload = \(\) => \{[\s\S]*window\.electron\.openExternal\(launcherUpdate\.downloadUrl\)/)
  assert.match(appSource, /settings\.update\.prompt\.manualText/)
  assert.match(appSource, /settings\.update\.prompt\.manualLink/)
  assert.match(appSource, /window\.electron\.installLauncherUpdate\(\)/)
  assert.match(appSource, /settings\.update\.prompt\.readyNotice/)
  assert.doesNotMatch(appSource, /window\.electron\.applyLauncherUpdate\(\)/)
  assert.match(appSource, /settings\.update\.prompt\.opening/)
  assert.match(appSource, /settings\.update\.prompt\.opened/)
  assert.match(appSource, /settings\.update\.prompt\.openAgain/)
  assert.doesNotMatch(appSource, /launcherUpdateInstallState !== 'applying'/)
  assert.doesNotMatch(appSource, /Math\.min\(92, current \+ 4\)/)
  assert.match(appSource, /settings\.update\.prompt\.notNow/)
  assert.match(appSource, /const launcherUpdateSteps = \[/)
  assert.match(appSource, /settings\.update\.prompt\.step\.download/)
  assert.match(appSource, /settings\.update\.prompt\.step\.open/)
  assert.match(appSource, /launcherUpdateSteps\.map\(\(label, index\) =>/)
  assert.match(appSource, /max-h-\[calc\(100vh-32px\)\][\s\S]*max-w-lg/)
  assert.match(appSource, /min-h-0 flex-1 space-y-3 overflow-y-auto p-4/)
  assert.match(appSource, /max-h-32 overflow-y-auto/)
  assert.match(appSource, /flex shrink-0 flex-col-reverse/)
  assert.match(updaterSource, /getLauncherInstallerTempPath/)
  assert.match(updaterSource, /buildLauncherInstallerTempPath\(/)
  assert.match(updaterSource, /\$\{process\.pid\}-\$\{Date\.now\(\)\}-\$\{crypto\.randomUUID\(\)\}/)
  assert.match(updaterSource, /getLauncherInstallerFallbackPath/)
})

test('shows an immediate launcher splash and MiniSand partner details in About', () => {
  assert.match(indexHtml, /class="nam-initial-splash"/)
  assert.match(indexHtml, /src="\.\/namlauncher-icon\.png"/)
  assert.match(indexHtml, /NamLauncher/)
  assert.match(mainSource, /function createLauncherStartupSplashHtml\(iconPath\?: string\)/)
  assert.match(mainSource, /pathToFileURL\(iconPath\)\.toString\(\)/)
  assert.match(mainSource, /show: false/)
  assert.match(mainSource, /backgroundColor: '#07111f'/)
  assert.match(mainSource, /data:text\/html;charset=UTF-8/)
  assert.match(mainSource, /setTimeout\(loadLauncherRenderer, 120\)/)
  assert.match(appSource, /PARTNER_SERVERS\.map\(\(server\) =>/)
  assert.match(appSource, /openPartnerServerWebsite\(server\)/)
  assert.match(appSource, /src=\{server\.iconUrl\}/)
  assert.match(partnerServersSource, /name: 'MiniSand'[\s\S]*websiteUrl: 'https:\/\/minisand\.online\/'/)
  assert.match(partnerServersSource, /name: 'MiniSand'[\s\S]*iconUrl: '\.\/minisand-logo\.png'/)
  assert.match(appSource, /settings\.about\.developerName/)
  assert.match(appTextSource, /'settings\.about\.developerName': 'Nattapat2871'/)
  assert.match(appTextSource, /'settings\.about\.partnerName': 'MiniSand Online'/)
})

test('tracks and stops Minecraft processes independently per instance', () => {
  assert.match(mainSource, /const runningGames = new Map<string, RunningGame>\(\)/)
  assert.match(mainSource, /const activeLaunches = new Map<string, LaunchSession>\(\)/)
  assert.match(mainSource, /const LAUNCH_STALE_TIMEOUT_MS = 20 \* 60 \* 1000/)
  assert.match(mainSource, /const cleanupStaleLaunches = \(\) => \{/)
  assert.match(mainSource, /runningGames\.has\(instance\.id\)/)
  assert.match(mainSource, /activeLaunches\.set\(instance\.id, launchSessionState\)/)
  assert.match(mainSource, /alreadyLaunching: true/)
  assert.match(appSource, /result\?\.alreadyLaunching/)
  assert.match(mainSource, /trustedIpcHandle\('stop-minecraft'[\s\S]*requestedInstanceId/)
  assert.match(preloadSource, /stopMinecraft: \(instance\?: any\)/)
  assert.match(appSource, /stopMinecraft\(target\)/)
})

test('keeps Microsoft accounts refreshable across launcher restarts', () => {
  assert.match(mainSource, /MICROSOFT_AUTH_REFRESH_GRACE_SECONDS/)
  assert.match(mainSource, /const getMicrosoftRefreshToken = \(auth: any\)/)
  assert.match(mainSource, /const mergeMicrosoftAuthorizationState = \(previousAuth: any, nextAuth: any\)/)
  assert.match(mainSource, /\.\.\.previousSession,[\s\S]*\.\.\.nextSession,[\s\S]*\.\.\.\(refreshToken \? \{ refresh: refreshToken \} : \{\}\)/)
  assert.match(mainSource, /shouldRefreshMicrosoftAuthorization\(account\.auth\)/)
  assert.match(mainSource, /Microsoft login did not return a refresh token/)
  assert.match(mainSource, /missing its refresh token/)
})

test('logs out expired Microsoft accounts and prompts for a fresh sign in', () => {
  assert.match(mainSource, /const notifyAccountSessionExpired = \(account: StoredAccount, message: string\) => \{/)
  assert.match(mainSource, /removeStoredAccount\(account\.id\)/)
  assert.match(mainSource, /Microsoft account secure storage is unavailable/)
  assert.doesNotMatch(mainSource, /Falling back to plain storage/)
  assert.match(mainSource, /fs\.chmodSync\(filePath, 0o600\)/)
  assert.match(mainSource, /const toAccountSummary[\s\S]*id: account\.id[\s\S]*updatedAt: account\.updatedAt/)
  assert.match(mainSource, /clientSecret\|client_secret\|password/)
  assert.match(mainSource, /authorization\|proxy-authorization\|cookie\|set-cookie/)
  assert.match(mainSource, /const normalizeLoaderPathIdentifier/)
  assert.match(mainSource, /Fabric profile ID/)
  assert.match(mainSource, /NeoForge profile ID/)
  assert.match(mainSource, /assertPathWithinRoot\(loaderDir, installerPath\)/)
  assert.match(mainSource, /webContents\.send\('account-session-expired'/)
  assert.match(mainSource, /isMicrosoftSessionAuthenticationFailure\(err\)/)
  assert.match(preloadSource, /onAccountSessionExpired/)
  assert.match(preloadSource, /ipcRenderer\.on\('account-session-expired'/)
  assert.match(appSource, /sessionExpiredNotice/)
  assert.match(appSource, /showMicrosoftSessionExpired/)
  assert.match(appSource, /window\.electron\.onAccountSessionExpired/)
  assert.match(appSource, /auth\.sessionExpired\.title/)
})

test('adds screenshots and drag-and-drop imports to instance content', () => {
  assert.match(mainSource, /type InstanceContentKind = 'mods' \| 'resourcepacks' \| 'shaderpacks' \| 'screenshots'/)
  assert.match(mainSource, /if \(kind === 'screenshots'\) return path\.join\(gameDirectory, 'screenshots'\)/)
  assert.match(mainSource, /kind === 'screenshots'[\s\S]*png\|jpe\?g\|webp/)
  assert.match(mainSource, /const importInstanceContentFiles = \(request: InstanceContentRequest\) => \{/)
  assert.match(mainSource, /trustedIpcHandle\('import-instance-content-files'/)
  assert.match(mainSource, /trustedIpcHandle\('reveal-instance-content-file'/)
  assert.match(mainSource, /const getInstanceContentId = \(contentDirectory: string, fileName: string\) =>/)
  assert.match(mainSource, /const fileName = String\(request\.fileName \|\| ''\)\.trim\(\)/)
  assert.match(mainSource, /const contentId = String\(request\.contentId \|\| ''\)\.trim\(\)\.toLowerCase\(\)/)
  assert.match(mainSource, /const filePath = path\.join\(contentDirectory, fileName\)/)
  assert.doesNotMatch(mainSource, /const filePath = String\(request\.filePath/)
  assert.match(mainSource, /const assertArchiveContentReadable = \(filePath: string, kind: InstanceContentKind\) =>/)
  assert.match(mainSource, /new AdmZip\(filePath\)[\s\S]*zip\.getEntries\(\)/)
  assert.match(mainSource, /assertArchiveContentReadable\(sourcePath, kind\)/)
  assert.match(mainSource, /not a valid ZIP\/JAR archive/)
  assert.match(mainSource, /Could not read content metadata for \$\{filePath\}: \$\{detail\}/)
  assert.doesNotMatch(mainSource, /Could not read content metadata for \$\{filePath\}`, err/)
  assert.match(preloadSource, /webUtils\.getPathForFile/)
  assert.match(preloadSource, /importInstanceContentFiles: \(options: any\) => invoke\('import-instance-content-files'/)
  assert.match(preloadSource, /revealInstanceContentFile: \(options: any\) => invoke\('reveal-instance-content-file'/)
  assert.match(preloadSource, /Content selection is no longer current/)
  assert.match(appSource, /fileName: item\.fileName,[\s\S]*contentId: item\.id/)
  assert.match(appSource, /type InstanceContentKind = 'mods' \| 'resourcepacks' \| 'shaderpacks' \| 'screenshots'/)
  assert.match(appSource, /const instanceContentTabs: Array<\{ id: InstanceContentKind; label: string; folder: string \}> = INSTANCE_CONTENT_KINDS\.map/)
  assert.match(appSource, /label: getContentTabLabel\(id\)/)
  assert.match(appTextSource, /'content\.tab\.screenshots': 'Screenshots'/)
  assert.match(appSource, /const importDroppedContentFiles = async \(files: File\[\]\) => \{/)
  assert.match(appSource, /window\.electron\.getDroppedFilePaths\(files\)/)
  assert.match(appSource, /window\.electron\.importInstanceContentFiles/)
  assert.match(appSource, /const showingScreenshots = currentContentTab\.id === 'screenshots'/)
  assert.match(appSource, /aria-label=\{t\('content\.showFolder'\)\}/)
})

test('keeps Library search responsive and flips installed state immediately after install', () => {
  assert.match(appSource, /const LIBRARY_SEARCH_DEBOUNCE_MS = 150/)
  assert.match(appSource, /const LIBRARY_SEARCH_CACHE_TTL_MS = 5 \* 60 \* 1000/)
  assert.match(appSource, /const LIBRARY_SEARCH_CACHE_LIMIT = 40/)
  assert.match(appSource, /librarySearchCacheRef\.current\.get\(cacheKey\)/)
  assert.match(appSource, /setLibraryLoading\(!hasFreshCache\)/)
  assert.match(appSource, /librarySearchCacheRef\.current\.set\(cacheKey, \{ hits, total_hits: total, storedAt: Date\.now\(\) \}\)/)
  assert.match(appSource, /if \(cancelled \|\| result\?\.canceled\) return/)
  assert.match(appSource, /librarySearchCacheRef\.current\.size > LIBRARY_SEARCH_CACHE_LIMIT/)
  assert.match(mainSource, /const PROJECT_SEARCH_CACHE_TTL_MS = 5 \* 60 \* 1000/)
  assert.match(mainSource, /const PROJECT_SEARCH_CACHE_LIMIT = 80/)
  assert.match(mainSource, /const MODRINTH_VERSION_CACHE_TTL_MS = 2 \* 60 \* 1000/)
  assert.match(mainSource, /const getCachedProjectSearchResult = \(cacheKey: string, allowStale = false\) =>/)
  assert.match(mainSource, /setCachedProjectSearchResult\(cacheKey, normalizedResult\)/)
  assert.match(mainSource, /setCachedProjectSearchResult\(cacheKey, result\)/)
  assert.match(appSource, /installedContentStatusOverridesRef\.current = \{\}/)
  assert.match(appSource, /const projectId = getProjectKey\(project\)/)
  assert.match(appSource, /const installedStatus: ContentStatus = \{[\s\S]*state: status\?\.latestVersionId[\s\S]*\? 'update' : 'installed'/)
  assert.match(appSource, /setContentStatuses\(\(prev\) => \(\{ \.\.\.prev, \[projectId\]: installedStatus \}\)\)/)
  assert.match(appSource, /setContentStatuses\(\{ \.\.\.statuses, \.\.\.installedContentStatusOverridesRef\.current \}\)/)
  assert.doesNotMatch(appSource, /\.then\(setContentStatuses\)/)
  assert.doesNotMatch(appSource, /contentStatusLoading && !status/)
  assert.match(appSource, /className="pointer-events-none absolute inset-y-0 right-3 flex items-center"[\s\S]*className="animate-spin text-blue-300"/)
  assert.doesNotMatch(appSource, /right-3 top-1\/2 -translate-y-1\/2 animate-spin text-blue-300/)
  assert.match(mainSource, /if \(!installed \|\| !recordFilesExist\(installed\)\) \{[\s\S]*state: 'install'/)
})

test('ignores stale manifest files outside the active instance during Modrinth updates', () => {
  assert.match(mainSource, /if \(!isPathInside\(previousPath, gameDirectory\)\) \{/)
  assert.match(mainSource, /Ignored stale content manifest path outside the active instance/)
  assert.doesNotMatch(mainSource, /assertChildPathIsSafe\(gameDirectory, previousPath\)/)
})

test('recovers legacy Thai font resource packs that can crash Minecraft', () => {
  assert.match(mainSource, /const THAI_RESOURCE_PACK_FILE = 'NamLauncher-Thai-Font\.zip'/)
  assert.match(mainSource, /const LEGACY_THAI_RESOURCE_PACK_FILES = \['Th-En-Font\.zip'\]/)
  assert.match(mainSource, /const LEGACY_THAI_RESOURCE_PACK_ENTRIES =/)
  assert.match(mainSource, /legacyResourcePackIds/)
  assert.match(mainSource, /filename\.replace\(\/\\\.zip\$\/i, ''\)/)
  assert.match(mainSource, /values\.filter\(\(value\) => !legacyResourcePackIds\.has\(value\)\)/)
  assert.match(mainSource, /Disabled legacy NamLauncher Thai font resource pack/)
  assert.match(mainSource, /fs\.renameSync\(legacyPath, quarantinePath\)/)
  assert.match(mainSource, /const disableManagedThaiResourcePacksInOptions =/)
  assert.match(mainSource, /Could not refresh the managed Thai font resource pack[\s\S]{0,360}disableManagedThaiResourcePacksInOptions\(gameDirectory\)/)
})

test('ships a verified Thai font pack whose metadata is valid across supported modern versions', async () => {
  const archivePath = fileURLToPath(new URL('../build/resourcepacks/NamLauncher-Thai-Font.zip', import.meta.url))
  const archiveBytes = await readFile(archivePath)
  const archive = new AdmZip(archiveBytes)
  const metadataEntry = archive.getEntry('pack.mcmeta')
  assert.ok(metadataEntry)
  const metadata = JSON.parse(metadataEntry.getData().toString('utf8'))
  assert.equal(metadata.pack.pack_format, 84)
  assert.deepEqual(metadata.pack.supported_formats, [15, 999])
  assert.equal(metadata.pack.min_format, 15)
  assert.equal(metadata.pack.max_format, 999)

  const sha256 = crypto.createHash('sha256').update(archiveBytes).digest('hex')
  assert.match(mainSource, new RegExp(`const THAI_RESOURCE_PACK_SHA256 = '${sha256}'`))
})

test('keeps launcher error reports scrollable and includes player hardware metadata', () => {
  assert.match(mainSource, /type LauncherStorageDevice = \{/)
  assert.match(mainSource, /const getStorageReportInfo = async/)
  assert.match(mainSource, /settleWithin\(getStorageReportInfo\(\), ERROR_REPORT_HARDWARE_TIMEOUT_MS/)
  assert.match(mainSource, /storage\s*\n\s*\}/)
  assert.match(mainSource, /playerName: normalizeErrorReportPlayerName/)
  assert.match(appSource, /const getLauncherErrorReportMetaLines = \(report: LauncherErrorReport\) => \{/)
  assert.match(appSource, /`Player: \$\{report\.playerName \|\| activeAccount\?\.name \|\| 'unknown'\}`/)
  assert.match(appSource, /`Storage: \$\{storageSummary \|\| 'unknown'\}`/)
  assert.match(appSource, /className="flex h-\[calc\(100vh-24px\)\] w-full max-w-5xl flex-col overflow-hidden/)
  assert.match(appSource, /max-h-36 shrink-0[\s\S]*overflow-y-auto/)
  assert.match(appSource, /wrap="off"/)
  assert.match(appSource, /cursor-text resize-none overflow-auto/)
})

test('uses a public report-only token fallback consistently across launcher builds', async () => {
  const viteConfig = await readFile(new URL('../vite.config.ts', import.meta.url), 'utf8')
  const envUtils = await readFile(new URL('../scripts/env-utils.mjs', import.meta.url), 'utf8')
  const workflow = await readFile(new URL('../.github/workflows/build-desktop.yml', import.meta.url), 'utf8')
  const token = 'namlauncher-error-report-public-v1-nattapat2871'
  assert.match(mainSource, new RegExp(token))
  assert.match(viteConfig, new RegExp(token))
  assert.match(envUtils, new RegExp(token))
  assert.match(workflow, /NAMLAUNCHER_ERROR_REPORT_TOKEN: \$\{\{ secrets\.NAMLAUNCHER_ERROR_REPORT_TOKEN \}\}/)
})

test('turns completed CurseForge manual downloads into a ready-to-play state', () => {
  assert.match(appSource, /manualDownloadCompletionAnnouncedRef/)
  assert.match(appSource, /manualDownloadItems\.every\(\(item\) => manualDownloadStatuses\[item\.id\] === 'complete'\)/)
  assert.match(appSource, /manualDownload\.ready\.status/)
  assert.match(appSource, /manualDownloadAllComplete/)
  assert.match(appSource, /manualDownload\.ready\.play/)
  assert.match(appSource, /handleLaunchOrStop\(instance\)\.catch/)
  assert.match(appTextSource, /'manualDownload\.ready\.title': 'All CurseForge files are ready'/)
  assert.match(appTextSource, /'manualDownload\.ready\.play': 'Play now'/)
})
